### ISSUE TITLE
Question about IC4

### ISSUE THREAD

**Issue by jongallant** [tebl/C64-Pi1541-Module#1]
What is the IC4 SSD1306 OLED-display 128x32 (0.91") ?  Is this optional? 

Sorry don't know how else to contact you.

**Comment by tebl** [comment]
Hope you found the solution before long, I have got to find out how to get github to notify me of things before I randomly stumble across things 4 months too late.

Anyway, the displays come in several sizes - most commonly 128x32 and 128x64. The smaller, and faster for the pi1541 since there are less pixels, have pins on the left side while the taller have them at the top. The PCB therefore will have an extra IC spot.

**Comment by jongallant** [comment]
Better late than never.  Thanks.
